version: 2.1

commands:
  pagerduty_fail_notify:
    description: Creates a PagerDuty incident on master build failure
    steps:
      - run:
          name: Create PagerDuty Incident
          when: on_fail
          command: |
            if [ $CIRCLE_JOB != 'the-job-x' ]; then
              curl \
                -X POST https://events.pagerduty.com/v2/enqueue \
                --data '{
                  "routing_key":"'${PAGERDUTY_ROUTING_KEY}'",
                  "event_action":"trigger",
                  "dedup_key":"'${CIRCLE_BUILD_NUM}'",
                  "payload":{
                    "summary":"Master build #'${CIRCLE_BUILD_NUM}' failed at job '${CIRCLE_JOB}'",
                    "source":"'${CIRCLE_WORKFLOW_ID}'",
                    "severity":"warning"
                  },
                  "links": [
                    {
                      "href": "'${CIRCLE_BUILD_URL}'",
                      "text": "Circle CI Build"
                    }
                  ]
                }'
            fi

jobs:
  the-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo "hello"
      - run :
          command: barf
      - pagerduty_fail_notify

workflows:
  the-workflow:
    jobs:
      - the-job